<a href="https://colab.research.google.com/github/Manish7031/deep-learning-pytorch-framework/blob/main/pytorch_fundamentals_1_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## pytorch fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cu128


### Tensor

In [2]:
scalar = torch.tensor(10)
scalar

tensor(10)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

10

In [5]:
vector = torch.tensor([4,4])
vector

tensor([4, 4])

In [6]:
vector.shape

torch.Size([2])

In [8]:
MATRIX = torch.tensor([[1,2],[3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
TENSOR =torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [11]:
TENSOR.shape

torch.Size([1, 3, 3])

### random tensor

In [14]:
random_tensor = torch.rand(1,3,3)
random_tensor

tensor([[[0.5945, 0.4210, 0.9097],
         [0.7005, 0.2350, 0.0856],
         [0.9885, 0.5422, 0.1883]]])

In [15]:
random_tensor.shape

torch.Size([1, 3, 3])

In [16]:
random_image_tensor = torch.rand(size=(3,224,224))
random_image_tensor.shape

torch.Size([3, 224, 224])

In [19]:
zeros= torch.zeros(3,4)
zeros
ones= torch.ones(3,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [22]:
rng = torch.range(1.0,10.0,2)
rng

/tmp/ipython-input-3276148827.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  rng = torch.range(1.0,10.0,2)


tensor([1., 3., 5., 7., 9.])

In [23]:
arrage1 = torch.arange(1,10,2)
arrage1

tensor([1, 3, 5, 7, 9])

### tensor datatypes

In [6]:
float16_tensor = torch.tensor([1.0,  2.0, 3.0],
                              dtype=torch.float16,
                              device=None,
                              requires_grad=False)
float16_tensor.dtype

torch.float16

In [8]:
float32_tensor = torch.tensor([4.0,5.0,6.0],
                              dtype=torch.float32,
                              device=None,
                              requires_grad=False)

In [9]:
multi = float16_tensor * float32_tensor
multi

tensor([ 4., 10., 18.])

In [10]:
multi.device

device(type='cpu')

### tensors operations

In [11]:
tensor = torch.tensor([10,20,30])
tensor + 10

tensor([20, 30, 40])

In [12]:
tensor -10

tensor([ 0, 10, 20])

In [13]:
tensor * 2.5

tensor([25., 50., 75.])

### MATRIX multi

In [15]:
print(f"element wise multiplication : {tensor * tensor}")

MATRIX multiplication : tensor([100, 400, 900])


In [21]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 430 µs, sys: 0 ns, total: 430 µs
Wall time: 335 µs


tensor(1400)

In [29]:
tensorA = torch.tensor([[1,2],
                       [2,3],
                       [3,4]])

tensorB = torch.tensor([[5,6],
                       [6,7],
                       [7,8]])
print("output => ")
torch.matmul(tensorA, tensorB.T), torch.matmul(tensorA, tensorB.T).shape, torch.matmul(tensorA, tensorB.T).dtype

output => 


(tensor([[17, 20, 23],
         [28, 33, 38],
         [39, 46, 53]]),
 torch.Size([3, 3]),
 torch.int64)

### tensor aggregation

In [42]:
tensor_agg = torch.rand(3,3)
print(tensor_agg)
print(f"tensor dtype: {tensor_agg.dtype}")
print(f"min value : {torch.min(tensor_agg)}")
print(f"max value : {torch.max(tensor_agg)}")
print(f"mean value : {torch.mean(tensor_agg)}")
print(f"sum : {torch.sum(tensor_agg)}")
print(f"positional min : {torch.argmin(tensor_agg)}")
print(f"positional max : {torch.argmax(tensor_agg)}")


tensor([[0.1563, 0.3138, 0.7470],
        [0.6429, 0.5799, 0.8771],
        [0.0577, 0.0520, 0.3402]])
tensor dtype: torch.float32
min value : 0.05202805995941162
max value : 0.8770936131477356
mean value : 0.4185434579849243
sum : 3.7668910026550293
positional min : 7
positional max : 5


### tensor reshaping, stacking, squeezing, unsqueezing, permute

In [2]:
tensor_X =torch.rand(1,10)
print(tensor_X)
print(f"tensor dtype : {tensor_X.dtype}")
print(f"\nshape : {tensor_X.shape}")
print(f"\nreshape : {tensor_X.reshape(10,1)}")
print(f"\nstacks : {torch.stack([tensor_X, tensor_X, tensor_X], dim=0)}")
print(f"\nsequeeze : {torch.squeeze(tensor_X)} \nsqueeze size :  {torch.squeeze(tensor_X).shape}")
print(f"\nunsqueeze : {torch.unsqueeze(tensor_X, dim=0)}")
print(f"\npermute : {torch.permute(tensor_X, (-2,1))}")

tensor([[0.3049, 0.0141, 0.9840, 0.5930, 0.9858, 0.8529, 0.8954, 0.4031, 0.0835,
         0.5860]])
tensor dtype : torch.float32

shape : torch.Size([1, 10])

reshape : tensor([[0.3049],
        [0.0141],
        [0.9840],
        [0.5930],
        [0.9858],
        [0.8529],
        [0.8954],
        [0.4031],
        [0.0835],
        [0.5860]])

stacks : tensor([[[0.3049, 0.0141, 0.9840, 0.5930, 0.9858, 0.8529, 0.8954, 0.4031,
          0.0835, 0.5860]],

        [[0.3049, 0.0141, 0.9840, 0.5930, 0.9858, 0.8529, 0.8954, 0.4031,
          0.0835, 0.5860]],

        [[0.3049, 0.0141, 0.9840, 0.5930, 0.9858, 0.8529, 0.8954, 0.4031,
          0.0835, 0.5860]]])

sequeeze : tensor([0.3049, 0.0141, 0.9840, 0.5930, 0.9858, 0.8529, 0.8954, 0.4031, 0.0835,
        0.5860]) 
squeeze size :  torch.Size([10])

unsqueeze : tensor([[[0.3049, 0.0141, 0.9840, 0.5930, 0.9858, 0.8529, 0.8954, 0.4031,
          0.0835, 0.5860]]])

permute : tensor([[0.3049, 0.0141, 0.9840, 0.5930, 0.9858, 0.8529, 0.89

### tensor indexing

In [3]:
tensor_A = torch.arange(1,10).reshape(1,3,3)
tensor_A, tensor_A.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [7]:
tensor_A[0], tensor_A[0,0], tensor_A[0,0,0]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

In [8]:
tensor_A[0], tensor_A[0][0], tensor_A[0][0][0]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

In [19]:
tensor_A[0,2,2], tensor_A[0,0,:]

(tensor(9), tensor([1, 2, 3]))

### numpy to torch

In [24]:
###default numpy dtype is float64
arr = np.arange(1.0, 10.0)
tensor = torch.from_numpy(arr)
arr, tensor
arr + 10,tensor

(array([11., 12., 13., 14., 15., 16., 17., 18., 19.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

### pytorch Reproducibility - reduce randomness

In [2]:
random_seed = 42
torch.manual_seed(random_seed)
tensorA = torch.rand(3,3)

torch.manual_seed(random_seed)
tensorB = torch.rand(3,3)

print(tensorA)
print(tensorB)
print(tensorA == tensorB)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


### Run tensor on GPU

In [4]:
torch.cuda.is_available()

True

In [5]:
device = "cuda" if  torch.cuda.is_available() else "cpu"
device

'cuda'

In [6]:
torch.cuda.device_count()

1

In [7]:
## move tensor to GPU
tensor = torch.tensor([1,2,3])
tensor_gpu = tensor.to(device)
print("******* output ********")
tensor_gpu, tensor_gpu.cpu()

******* output ********


(tensor([1, 2, 3], device='cuda:0'), tensor([1, 2, 3]))

In [12]:
## exercise:
tensor_random1 = torch.rand(7,7)
tensor_random1, tensor_random1.shape

(tensor([[0.7530, 0.3675, 0.2035, 0.7307, 0.8067, 0.4084, 0.2503],
         [0.2956, 0.0820, 0.3725, 0.6889, 0.0242, 0.3983, 0.4653],
         [0.8731, 0.6633, 0.4801, 0.9170, 0.0011, 0.2540, 0.2233],
         [0.5342, 0.8097, 0.4864, 0.4805, 0.9430, 0.1727, 0.4164],
         [0.7316, 0.9299, 0.7266, 0.1071, 0.4631, 0.7281, 0.0975],
         [0.2174, 0.2562, 0.6207, 0.6250, 0.2055, 0.7882, 0.9114],
         [0.6301, 0.1734, 0.8305, 0.4419, 0.5684, 0.7081, 0.1863]]),
 torch.Size([7, 7]))

In [13]:
tensor_rand2 = torch.rand(1,7)
tensor_rand2, tensor_rand2.shape

(tensor([[0.7120, 0.0851, 0.5843, 0.6590, 0.1931, 0.0224, 0.6746]]),
 torch.Size([1, 7]))

In [16]:
print("multiply output*********")
print(tensor_random1 * tensor_rand2.T)

multiply output*********
tensor([[5.3614e-01, 2.6169e-01, 1.4488e-01, 5.2026e-01, 5.7443e-01, 2.9083e-01,
         1.7819e-01],
        [2.5164e-02, 6.9801e-03, 3.1712e-02, 5.8650e-02, 2.0638e-03, 3.3907e-02,
         3.9614e-02],
        [5.1013e-01, 3.8759e-01, 2.8051e-01, 5.3582e-01, 6.1386e-04, 1.4844e-01,
         1.3046e-01],
        [3.5205e-01, 5.3363e-01, 3.2053e-01, 3.1666e-01, 6.2145e-01, 1.1380e-01,
         2.7445e-01],
        [1.4128e-01, 1.7959e-01, 1.4031e-01, 2.0690e-02, 8.9428e-02, 1.4061e-01,
         1.8829e-02],
        [4.8713e-03, 5.7413e-03, 1.3911e-02, 1.4007e-02, 4.6065e-03, 1.7663e-02,
         2.0426e-02],
        [4.2506e-01, 1.1696e-01, 5.6026e-01, 2.9809e-01, 3.8342e-01, 4.7770e-01,
         1.2565e-01]])


In [18]:
random_seed = 1234
torch.manual_seed(random_seed)
tensorA1 = torch.rand(2,3)

torch.manual_seed(random_seed)
tensorB1 = torch.rand(2,3)
print(tensorA1)
print(tensorB1)

print("******* output **********")
print(tensorA1 * tensorB1)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
******* output **********
tensor([[0.0008, 0.1615, 0.0675],
        [0.1344, 0.0034, 0.4909]])
